siteTitle = "Blog by Yoni Davidson"
siteDescr = "TDD my way around the world"
siteAuthor = "Yoni Davidson"

siteTelegramUrl = "https://t.me/yonidavidson"
siteTwitterUrl = "https://twitter.com/yonidavidson"
siteGithubUrl = "https://github.com/yonidavidson"
siteEmailUrl = "yonidavidson@gmail.com"

googleAnalyticsId = "UA-97082010-1"

linkPrefix = "/blog"